name: Build

on: push

jobs:
  build:
    name: ImageConvert build
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest] #, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          check-latest: true
          cache: true
          go-version: "1.23"

      - name: Install dependencies
        uses: ConorMacBride/install-package@v1
        with:
          brew: jpegoptim imagemagick
          apt: jpegoptim imagemagick
          choco: jpegoptim ImageMagick

      - name: Prepare
        run: |
          go clean -r ./...
          go mod tidy

      - name: Test
        run: |
          go test -v -race -count 1 -parallel 50 -covermode=atomic -coverprofile="coverage.out" ./...

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true # optional (default = false)

      - name: Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          args: --timeout=5m

      - name: Build 
        run: |
          make build

      - name: Govulncheck
        uses: kmulvey/govulncheck-action@v1.3.0
